spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: identity_user
    password: identity_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
    open-in-view: false

  flyway:
    enabled: true
    default-schema: auth
    schemas: auth

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
